const ECONOMY = 1;
const POLITICS = 2;
const INTERNATIONAL = 3;
const SOCIAL = 4;
const CULTURE = 5;

module.exports = {
  ALL: [ECONOMY, POLITICS, SOCIAL, INTERNATIONAL, CULTURE],
  ECONOMY,
  POLITICS,
  SOCIAL,
  INTERNATIONAL,
  CULTURE,
};
