const POLITIC = 2;
const ECONOMY = 3;
const TECHNOLOGY = 4;
const ENVIRONMENT = 5;
const SCIENCE = 6;
const HEALTH = 7;
const SPORTS = 8;

module.exports = {
  ALL: [1, POLITIC, ECONOMY, TECHNOLOGY, ENVIRONMENT, SCIENCE, HEALTH, SPORTS],
  POLITIC,
  ECONOMY,
  TECHNOLOGY,
  ENVIRONMENT,
  SCIENCE,
  HEALTH,
  SPORTS,
};
