const POLITIC = 2;
const ECONOMY = 3;
const SOCIETY = 4;
const INTERNATIONAL = 5;
const CULTURE = 6;

module.exports = {
  ALL: [1, POLITIC, ECONOMY, SOCIETY, INTERNATIONAL, CULTURE],
  POLITIC,
  ECONOMY,
  SOCIETY,
  INTERNATIONAL,
  CULTURE,
};