const ECONOMY = 2;
const POLITICS = 3;
const INTERNATIONAL = 4;
const SOCIAL = 5;
const CULTURE = 6;

module.exports = {
  ALL: [1, POLITICS, ECONOMY, SOCIAL, INTERNATIONAL, CULTURE],
  POLITICS,
  ECONOMY,
  SOCIAL,
  INTERNATIONAL,
  CULTURE,
};