name: remote ssh command for deploy
on:
  push:
    branches: [develop]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          ./deploy-dev.sh

