version: '3'

services:
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    volumes:
      - ./srcs/conf.d:/etc/mysql/conf.d
      - ./srcs/data:/var/lib/mysql
      - ./srcs/initdb.d:/docker-entrypoint-initdb.d
    env_file: ../.env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend:
